[package]
name = "temple"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tem"
path = "src/main.rs"

[lib]
name = "tem_p"
path = "src/lib.rs"

[dependencies]
fs_extra = "1.2.0"
directories = "4.0.1"
smartstring = "1.0.1"
clap = { version = "3.1.8", default_features = false, features = ["derive", "std"] }

[dev-dependencies]
iai = "0.1.1"
criterion = "0.3.5"

[[bench]]
name = "criterion"
harness = false

[[bench]]
name = "iai"
harness = false