[package]
name="temple"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
fs_extra = "1.2.0"
directories = "4.0.1"
smartstring = "1.0.1"

[dev-dependencies]
iai = "0.1.1"
criterion = "0.3.5"

[[bench]]
name = "criterion"
harness = false
